from typing import Final

RSS_FEEDS: Final[tuple[str, ...]] = (
    # --- AP & Music Journalism ---
    "https://apnews.com/hub/music/rss",
    "https://www.npr.org/rss/rss.php?id=1039",
    "https://www.billboard.com/feed/",
    "https://pitchfork.com/feed/feed-news/rss",
    "https://www.rollingstone.com/feed/",
    "https://www.spin.com/feed/",
    "https://www.pastemagazine.com/music/rss",
    "https://consequence.net/feed/",
    "https://www.brooklynvegan.com/feed/",
    "https://www.stereogum.com/category/news/feed/",
    "https://www.thefader.com/feeds/main",
    "https://www.classicfm.com/music-news/rss/",
    "https://www.grammy.com/rss.xml",
    "https://www.musicbusinessworldwide.com/feed",
    "https://www.factmag.com/feed",

    # --- AP & Tourist Journalism (Travel) ---
    "https://apnews.com/hub/travel/rss",
    "https://www.atlasobscura.com/feeds/latest",
    "https://www.nationalgeographic.com/travel/rss-feed",
    "https://www.lonelyplanet.com/news/feed/atom/",
    "https://www.travelandleisure.com/travel/rss",
    "https://www.cntraveler.com/feed/rss",
    "https://adventure.com/feed/",
    "https://matadornetwork.com/feed/",
    "https://www.nomadicmatt.com/travel-blog/feed/",
    "https://www.ricksteves.com/watch-read-listen/read/travel-news/rss.xml",
    "https://www.fodors.com/news/rss",
    "https://www.frommers.com/rss",
    "https://www.roadsandkingdoms.com/feed",
    "https://www.smithsonianmag.com/rss/travel/",
    "https://www.afar.com/feed/atom",

    # --- AP & US City/State Local News Feeds ---
    "https://www.al.com/arc/outboundfeeds/rss/?outputType=xml",
    "https://www.adn.com/arc/outboundfeeds/rss/",
    "https://www.azcentral.com/rss/news",
    "https://www.arkansasonline.com/rss/headlines/",
    "https://www.latimes.com/index.rss",
    "https://www.denverpost.com/feed/",
    "https://www.courant.com/arcio/rss/",
    "https://www.delawareonline.com/rss/news",
    "https://www.tampabay.com/arc/outboundfeeds/rss/category/news/?outputType=xml",
    "https://www.ajc.com/arc/outboundfeeds/rss/",
    "https://www.staradvertiser.com/feed/",
    "https://www.idahostatesman.com/news/rss/",
    "https://www.chicagotribune.com/rss",
    "https://www.indystar.com/rss/news",
    "https://www.desmoinesregister.com/rss/news",
    "https://www.kansas.com/news/rss/",
    "https://www.courier-journal.com/rss/news",
    "https://www.theadvocate.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.pressherald.com/feed/",
    "https://www.baltimoresun.com/rss/",
    "https://www.bostonglobe.com/feed",
    "https://www.freep.com/rss/news",
    "https://www.startribune.com/rss/",
    "https://www.clarionledger.com/rss/news",
    "https://www.stltoday.com/search/?f=rss&t=article&c=news&l=50",
    "https://billingsgazette.com/search/?f=rss&t=article&c=news&l=50",
    "https://omaha.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.reviewjournal.com/feed/",
    "https://www.unionleader.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.nj.com/arc/outboundfeeds/rss/?outputType=xml",
    "https://www.abqjournal.com/feed",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/section/nyregion/rss.xml",
    "https://www.newsobserver.com/news/rss/",
    "https://www.inforum.com/news/rss",
    "https://www.dispatch.com/rss/news",
    "https://oklahoman.com/feed",
    "https://www.oregonlive.com/arc/outboundfeeds/rss/",
    "https://www.inquirer.com/arc/outboundfeeds/rss/category/news/",
    "https://www.providencejournal.com/rss/news",
    "https://www.postandcourier.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.argusleader.com/rss/news",
    "https://www.tennessean.com/rss/news",
    "https://www.dallasnews.com/feed",
    "https://www.sltrib.com/arc/outboundfeeds/rss/?outputType=xml",
    "https://vtdigger.org/feed/",
    "https://richmond.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.seattletimes.com/feed/",
    "https://www.wvgazettemail.com/search/?f=rss&t=article&c=news&l=50",
    "https://www.jsonline.com/rss/news",
    "https://www.wyomingnews.com/news/rss.xml",

)
